export default [
    {
      archieved:false,
      id:"7",
      name: "edsfdf",
      createdAt: "11.02.2011",
      category: "task",
      content: "aehjkfdk",
      dates: ["01.09.2033"],
    },
    {

      id:"6",
      name: "edsfdf",
      createdAt: "01.01.2001",
      category: "randomThought",
      content: "Lolopol",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {

      id:"4",
      name: "edsfdf",
      createdAt: "11.11.2111",
      category: "idea",
      content: "aehjkfdk",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"5",
      name: "edsfdf",
      createdAt: "21.21.2121",
      category: "quote",
      content: "aehjkfdk",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"3",
      name: "edsfdf",
      createdAt: "21.21.2121",
      category: "task",
      content: "None",
      dates: ["01.09.2033"],
      archieved:true,
    },
    {
      id:"2",
      name: "edsfdf",
      createdAt: "21.21.2121",
      category: "task",
      content: "Bsnfkdf",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"1",
      name: "edsfdf",
      createdAt: "21.21.2121",
      category: "idea",
      content: "adskfdfdf",
      dates: ["01.09.2033"],
      archieved:true,
    },
  ];