export default [
    {
      id:"7",
      name: "Dima",
      createdAt: "11.02.2011",
      category: "task",
      content: "content",
      dates: ["01.09.2033"],
      archieved:false
    },
    {

      id:"6",
      name: "Vova",
      createdAt: "01.01.2001",
      category: "randomThought",
      content: "Lolopol",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {

      id:"4",
      name: "Kto to",
      createdAt: "11.11.2111",
      category: "idea",
      content: "play clah royale",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"5",
      name: "Noname",
      createdAt: "21.21.2121",
      category: "quote",
      content: "do nothing",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"3",
      name: "Vasya",
      createdAt: "21.21.2121",
      category: "task",
      content: "None",
      dates: ["01.09.2033"],
      archieved:true,
    },
    {
      id:"2",
      name: "My mom",
      createdAt: "21.21.2121",
      category: "task",
      content: "do smth",
      dates: ["01.09.2033"],
      archieved:false,
    },
    {
      id:"1",
      name: "Kirill",
      createdAt: "21.21.2121",
      category: "idea",
      content: "wake up",
      dates: ["01.09.2033"],
      archieved:true,
    },
  ];